from langgraph.graph import add_messages
from pydantic import BaseModel, Field
from typing import Annotated, Literal
from operator import add


class AgentState(BaseModel):
    user_question: str
    curated_question: str = ""
    prompt_query_context: str = ""
    generated_sql_query: str = ""
    is_safe: Literal["Yes", "No"] | None = None
    final_answer: str = ""
    comments: str = ""
    sql_query_execution_result: str = ""


class JudgeSchema(BaseModel):
    is_safe: Literal["Yes", "No"] | None = None

    comments: str = Field(
        ...,
        description="Explanation for why the SQL query was judged safe or unsafe."
    )

class ETLAgentState(BaseModel):
    user_question: str = ""
    messages: Annotated[list, add_messages] = Field(
        default_factory=list
    )

class DataAgentSchema(BaseModel):

    answer: Literal["sql", "etl"] = Field(..., description="The answer to the user's question, either 'sql' or 'etl'.")
    comment: str = Field(..., description="A comment explaining the reasoning behind the answer.")

class DataAgentState(BaseModel):
    messages: Annotated[list, add_messages] = Field(..., description="A list of messages exchanged between the user and the agent.")
    route_response: str = Field(..., description="The response generated by the LLM router based on the user's message.")